name: Build Package

on:
  push:
    tags:
      - v*

jobs:
  build_package:
    name: Build Package by uv
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
        python-version:
          # - "3.9"
          - "3.10"
          # - "3.11"
          # - "3.12"

    timeout-minutes: 20

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.0.0

      # - name: Setup SSH Key
      #   uses: shimataro/ssh-key-action@v2.7.0
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: unnecessary
      #     config: |
      #       Host *
      #         StrictHostKeyChecking no
      #         UserKnownHostsFile=/dev/null
      #     if_key_exists: replace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          pyproject-file: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          uv python pin ${{ matrix.python-version }}
          uv sync --no-dev

      - name: Get the version
        id: metadata
        uses: battila7/get-version-action@v2

      - name: Update Version
        shell: bash
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v ]]; then
            VERSION=$(date +%Y.%-m.%-d.%-H.%-M)
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Package
        run: |
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $VERSION
          uv build

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        env:
          OUTPUT: CHANGELOG.md
        with:
          config: pyproject.toml
          args: --unreleased --tag $VERSION
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./dist/*
          name: ${{ github.event.repository.name }}-packages
          if-no-files-found: ignore
          retention-days: 7
          compression-level: 6
          overwrite: true

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        # continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/*
