name: Build Package

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build_package:
    name: Build Package by Rye
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-20.04

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.0.0

      # - name: Setup SSH Key
      #   uses: shimataro/ssh-key-action@v2.7.0
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: unnecessary
      #     config: |
      #       Host *
      #         StrictHostKeyChecking no
      #         UserKnownHostsFile=/dev/null
      #     if_key_exists: replace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Setup Rye
        run: |
          make rye-install
          ~/.rye/shims/rye pin 3.10
          ~/.rye/shims/rye sync
          ~/.rye/shims/rye --version

      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        id: metadata
        uses: battila7/get-version-action@v2

      - name: Updaste Version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ~/.rye/shims/rye version ${{ steps.metadata.outputs.version }}

      - name: Replace Virtual Setting for Rye
        run: |
          sed -i 's/virtual = true/virtual = false/' pyproject.toml

      - name: Build Package
        run: |
          ~/.rye/shims/rye build --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./dist/*
          name: ${{ github.event.repository.name }}-packages
          if-no-files-found: ignore
          retention-days: 7
          compression-level: 6
          overwrite: true

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        # continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/*

      - name: Publish Package
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        env:
          PYPI_URL: https://test.pypi.org/legacy/
        run: |
          ~/.rye/shims/rye publish --repository ${{ github.repository }} --repository-url ${{ env.PYPI_URL }} --token ${{ secrets.PYPI_TOKEN }} -y

      - name: Publish package distributions to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ./dist
          verify-metadata: true
          skip-existing: true
          verbose: true
          print-hash: true
