name: pull-request-pipeline
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  auto-labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-latest  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - uses: actions/labeler@v4
        id: labeler
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: ''
          configuration-path: .github/labeler.yml
  gpt-reviewer:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    needs:
      - auto-labeler
    # container: catthehacker/ubuntu:act-latest  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo-16k'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
